Translate tutorial/tests
flaskcwg/flask-docs-zh pull request #109
Opened 2021-10-01 05:38 UTC by greyli

- [x] 在 README.md 中勾选翻译的章节条目（把方括号里的空格替换为 `x`）.
- [x] 在本地生成文档并预览输出，处理所有错误和异常。
- [x] 运行 `pre-commit` 钩子，处理所有问题。
- [x] 更新 `.po` 文件顶部的 `Last-Translator` 字段。
- [x] 如果你是第一个翻译者，同时更新 `.po` 文件顶部的 `FIRST AUTHOR <EMAIL@ADDRESS>`，替换为你的名字和 Email 地址。

2022-02-27 10:08 UTC, FesonX requested changes
审核完毕，按需修改，部分表述不够流畅

2022-02-27 10:08 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/tests.po
> +"你也可以在测试 ``index`` 视图时测试一些更多的认证行为。当未登录时，每一个页面会"
```suggestion
"你也可以在测试 ``index`` 视图时测试更多的认证行为。当未登录时，每一个页面会"
```

2022-02-27 10:08 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/tests.po
> +"有一些额外的配置可以添加到项目的 ``setup.cfg`` 文件。它们并不是必须的，但是可以简化运行"
```suggestion
"有一些额外的配置可以添加到项目的 ``setup.cfg`` 文件。它们并不是必须的，但是可以让"
```

2022-02-27 10:08 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/tests.po
> +"测试和计算覆盖率的命令，"
```suggestion
"测试和计算覆盖率简洁明了。"
```

2022-02-27 10:08 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/tests.po
> +"包含每一个测试函数的列表，而不仅仅显示点。"
```suggestion
"包含每一个测试函数的列表，而不只是显示一串点。"
```

2022-02-27 13:45 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/tests.po
> +"``login`` 视图的测试和 ``register`` 视图的测试非常相似。与其在数据库中"
啊，感谢指出！这里我没有读懂实际的意思。

2022-02-27 13:47 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/tests.po
> +"测试和计算覆盖率的命令，"
这里是不是还是使用原翻译比较好？我的理解是，这里添加一些配置到 setup.cfg，是为了让原本冗长的测试命令（需要很多参数）变得更简单。核心的意思是让测试的命令变得更短了。

2022-02-27 14:07 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/tests.po
> +"，然后为它们创建一个固件，并传递 ``client`` 固件给它。"
这里看[代码](https://flask.palletsprojects.com/en/2.0.x/tutorial/tests/#authentication)是在传递 client 固件给 auth 固件。

2022-02-28 01:11 UTC, FesonX approved these changes

2022-02-28 04:09 UTC, merged