Translate docs/patterns/favicon
flaskcwg/flask-docs-zh pull request #111
Opened 2021-10-08 11:41 UTC by ImJuanan

- [x] 在 README.md 中勾选翻译的章节条目（把方括号里的空格替换为 `x`）.
- [x] 在本地生成文档并预览输出，处理所有错误和异常。
- [x] 运行 `pre-commit` 钩子，处理所有问题。
- [x] 更新 `.po` 文件顶部的 `Last-Translator` 字段。
- [x] 如果你是第一个翻译者，同时更新 `.po` 文件顶部的 `FIRST AUTHOR <EMAIL@ADDRESS>`，替换为你的名字和 Email 地址。

2021-10-31 13:58 UTC, greyli requested changes
修正了几个标点问题。

2021-10-31 13:58 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/favicon.po
> +"来提供图标。请参考 web 服务器相关的文档。"
```suggestion
"来提供图标。请参考 web 服务器的文档。"
```

2021-10-31 13:58 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/favicon.po
> +"编写一个视图函数::"
```suggestion
"编写一个视图函数："
```

2021-10-31 13:58 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/favicon.po
> +"路由重定向至图标::"
```suggestion
"路由重定向至图标："
```

2021-10-31 13:58 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/favicon.po
> +"旧有的事实标准是在站点域名的根路径下提供以 :file:`favicon.ico` 命名的图标文件。"
```suggestion
"旧的事实标准是在站点域名的根路径下提供以 :file:`favicon.ico` 命名的图标文件。"
```

2021-11-01 11:40 UTC, FesonX approved these changes

2021-11-01 12:22 UTC, merged