Translate tutorial/views
flaskcwg/flask-docs-zh pull request #114
Opened 2021-10-13 03:37 UTC by greyli

Finally finished the translation of the whole tutorial.

2022-01-22 02:51 UTC, FesonX requested changes

2022-01-22 02:51 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/views.po
> +"在这种情况下，开始验证输入的数据。"
补充省略的主语
```suggestion
"在这种情况下，视图开始验证输入的数据。"
```

2022-01-22 02:51 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/views.po
> +"代表任意用户输入的 ``?`` 占位符，以及一个用来替换占位符的数据元组。"
翻译缺失
```suggestion
"代表任意用户输入的 ``?`` 占位符，以及一个用来替换占位符的数据元组。数据库相关的库"
"将负责转义值，使得你不易受到 *SQL 注入攻击*。
```

2022-01-22 02:51 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/views.po
> +"保存用户后，他们被重定向到登录页面。:func:`url_for` 根据其名称生成到 login 视图的 URL。"
这里用英文的 login 是为了与视图函数的名称匹配？

2022-01-22 02:51 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/views.po
> +"的下一章编写它。"
```suggestion
"的下一章编写相关代码。"
```

2022-01-22 02:51 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/views.po
> +"把它发送回来。Flask 对数据进行安全 *签名*，使其无法被篡改。"
不需要空格
```suggestion
"把它发送回来。Flask 对数据进行安全*签名*，使其无法被篡改。"
```

2022-01-22 02:51 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/views.po
> +"用户的 ID 是否存储在 :data:`session` 中，并从数据库中获取那个用户的数据，将其存储到 "
```suggestion
"用户的 ID 是否存储在 :data:`session` 中，并从数据库中获取对应用户的数据，将其存储到 "
```

2022-01-22 02:51 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/views.po
> +"创建、编辑和删除博客帖子将需要用户登录才能操作。可以使用一个 *装饰器* 来为每一个使用它的"
```suggestion
"创建、编辑和删除博客帖子将需要用户登录才能操作。可以使用一个*装饰器*来为每一个使用它的"
```

2022-01-22 02:51 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/views.po
> +"*端点（endpoint）*，默认它和视图函数的名称相同。"
```suggestion
"*端点（endpoint）*，默认情况下，它和视图函数的名称相同。"
```

2022-01-23 06:53 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/views.po
> +"把它发送回来。Flask 对数据进行安全 *签名*，使其无法被篡改。"
不加空格会导致 ReST 语法无法正确渲染（？）。

2022-01-23 06:59 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/views.po
> +"保存用户后，他们被重定向到登录页面。:func:`url_for` 根据其名称生成到 login 视图的 URL。"
改成了 code block 样式以便和其他几处一致。

2022-01-23 08:17 UTC, FesonX approved these changes

2022-01-23 08:20 UTC, merged

2022-01-23 08:20 UTC, greyli commented
@FesonX Thanks for the review!