Translate blueprints - frostming
flaskcwg/flask-docs-zh pull request #41
Opened 2021-05-28 05:56 UTC by frostming

- Error handler 采用了「错误处理器」的翻译

- [x] 在 README.md 中勾选翻译的章节条目（把方括号里的空格替换为 `x`）.
- [x] 在本地生成文档并预览输出，处理所有错误和异常。
- [x] 运行 `pre-commit` 钩子，处理所有问题。
- [x] 更新 `.po` 文件顶部的 `Last-Translator` 字段。

2021-06-12 11:03 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "使用蓝图的模块化应用"
这里的语义是指「使用蓝本来对应用进行模块化处理」，所以应译为「使用蓝本模块化应用」。

2021-06-12 14:40 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "使用蓝图的模块化应用"
```suggestion
msgstr "使用蓝图模块化应用"
```

2021-06-13 14:40 UTC, FesonX requested changes
翻译质量很高 :-) @frostming 
除了一些翻译建议，还有一些待讨论的点，欢迎说出各位的看法 @greyli

2021-06-13 14:40 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "Flask 中的蓝图有以下用途："
【待讨论】这里的 Cases 更适合译为场景？
[Flask 中的蓝图有以下用途：] -> [Flask 中的蓝图为以下场景设计：]

2021-06-13 14:40 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +"Flask 中的蓝图并非一个可插拔的应用，因为它压根不是一个应用——它是一组可注册在应用对象上"
【待讨论】压根有点口语化😝‘
[因为它压根不是一个应用] -> [因为它实际上并非一个应用]

2021-06-13 14:40 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +"的操作的集合，甚至可以注册多次。那么为什么不用多个应该对象呢？你可以这么做（参见 "
错别字
[那么为什么不用多个应该对象呢？] -> [那么为什么不使用多个应用对象呢？]

2021-06-13 14:40 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "蓝图的概念"
如果下文用了理念，那标题建议也复用同一翻译

2021-06-13 14:40 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +"关联起来，并且生成两个端点之间的 URL。"
这里的 When .. and ... 是一句接在上文的话，拆开在首尾似乎不太合适。
[分配请求时，Flask 会把蓝图和视图函数关联起来，并且生成两个端点之间的 URL。] -> [在分配请求及生成两个端点间的 URL 时，Flask 会把蓝图和视图函数关联起来。]

2021-06-13 14:40 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "如果你查看应用上注册的 URL 规则，你可以看到"
缺少冒号。
关于这种冒号，应该使用 msgid 中的双英文冒号 :: (会渲染为单英文冒号)还是单个中文冒号：呢？ @greyli @frostming

2021-06-13 14:40 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "如果你想在蓝图中暴露模板文件你可以给 :class:`Blueprint` 指定 `template_folder` 参数::"
加个逗号
[如果你想在蓝图中暴露模板文件，你可以给 :class:`Blueprint` 指定 `template_folder` 参数::]

2021-06-13 14:40 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "蓝图的错误处理"
**同上文意见，标题与内容一致。**
建议翻译为错误处理器

2021-06-13 14:40 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "下面是一个 “404 Page Not Found” 异常的例子::"
【待讨论】如果这里引用了英文原文，是否要使用英文引号？

2021-06-13 14:40 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +"``raise`` 语句或 ``abort`` 触发，而不能由，比方说，无效的 URL 访问触发。这是因为蓝图并不“拥有”某个 URL 空间，所以"
[而不能由，比方说，无效的 URL 访问触发] -> [而不能由类似无效的 URL 访问这种错误触发]

2021-06-14 12:13 UTC, frostming reviewed
@FesonX 感谢review，改正了许多不当之处。另外review时可用多suggested changes这个功能，原作者方便一键采纳。

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +"为了在一个或多个应用中支持模式复用，Flask 引入了蓝图的概念。蓝图可以极大地简化大型应用"
```suggestion
"为了在一个或多个应用中支持模式复用，Flask 引入了蓝图的概念。蓝图可以极大地简化大型应用的运作方式"
```

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "Flask 中的蓝图有以下用途："
```suggestion
msgstr "Flask 中的蓝图为以下场景设计："
```

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +"Flask 中的蓝图并非一个可插拔的应用，因为它压根不是一个应用——它是一组可注册在应用对象上"
```suggestion
"Flask 中的蓝图并非一个可插拔的应用，因为它实际上不是一个应用——它是一组可注册在应用对象上"
```

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +"Flask 中的蓝图并非一个可插拔的应用，因为它压根不是一个应用——它是一组可注册在应用对象上"
采纳，「不是」仍保留以免与上句的「并非」重复

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +"的操作的集合，甚至可以注册多次。那么为什么不用多个应该对象呢？你可以这么做（参见 "
```suggestion
"的操作的集合，甚至可以注册多次。那么为什么不用多个应用对象呢？你可以这么做（参见 "
```

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "蓝图的概念"
```suggestion
msgstr "蓝图的理念"
```

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +"关联起来，并且生成两个端点之间的 URL。"
```suggestion
"蓝图的基本理念是它记录了注册到应用之后将要执行的操作。在分配请求及生成两个端点间的URL时，"
"Flask 会把蓝图和视图函数关联起来。"
```

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "如果你查看应用上注册的 URL 规则，你可以看到"
```suggestion
msgstr "如果你查看应用上注册的 URL 规则，你可以看到::"
```

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "如果你查看应用上注册的 URL 规则，你可以看到"
::是代码块特殊标识，应保留

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "如果你想在蓝图中暴露模板文件你可以给 :class:`Blueprint` 指定 `template_folder` 参数::"
```suggestion
msgstr "如果你想在蓝图中暴露模板文件，你可以给 :class:`Blueprint` 指定 `template_folder` 参数::"
```

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "蓝图的错误处理"
```suggestion
msgstr "蓝图的错误处理器"
```

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +msgstr "下面是一个 “404 Page Not Found” 异常的例子::"
不认为应如此，中文排版标准里并没有直接双引号用英文的例子（除非是被引句子中的引号）

2021-06-14 12:13 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/blueprints.po
> +"``raise`` 语句或 ``abort`` 触发，而不能由，比方说，无效的 URL 访问触发。这是因为蓝图并不“拥有”某个 URL 空间，所以"
```suggestion
"``raise`` 语句或 ``abort`` 触发，而不能由类似于无效的 URL 访问这种错误触发。这是因为蓝图并不“拥有”某个 URL 空间，所以"
```

2021-06-20 02:09 UTC, FesonX approved these changes

2021-06-20 02:10 UTC, FesonX commented
@greyli 审核完毕

2021-08-28 01:39 UTC, merged

2021-08-28 03:40 UTC, greyli commented
@FesonX 先不用着急合并（至少两人 approved 后再合并）。