Translate appcontext
flaskcwg/flask-docs-zh pull request #43
Opened 2021-05-29 14:40 UTC by rosekc

- [x] 在 README.md 中勾选翻译的章节条目（把方括号里的空格替换为 `x`）.
- [x] 在本地生成文档并预览输出，处理所有错误和异常。
- [x] 运行 `pre-commit` 钩子，处理所有问题。
- [x] 更新 `.po` 文件顶部的 `Last-Translator` 字段。

2021-06-14 09:16 UTC, FesonX requested changes
**断句和语言的凝练方面有欠缺。**
另外一些原文的引用个人感觉长度是够的，不用将它们打断为两行
这个[中文文档](https://dormousehole.readthedocs.io/en/latest/index.html) 在翻译时可以看看

2021-06-14 09:16 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/appcontext.po
> +"在 ``g`` 的数据在上下文结束的时候会丢失，这不是两个请求之间存放数据的好地方。"
[在 ``g`` 的数据在上下文结束的时候会丢失，这不是两个请求之间存放数据的好地方。]
-> 
[在上下文结束的时候 ``g`` 对象中的数据会丢失，因此这不是存放请求之间数据的好地方。]

2021-06-15 08:20 UTC, rosekc commented on docs/locales/zh_CN/LC_MESSAGES/appcontext.po
> +"patterns/appfactories>` 、编写可重用的 :doc:`blueprints </blueprints>` 或者 :"
这里的 doc tag 应该会在 #41 合并后自动填入翻译后的标题。

2021-06-15 08:21 UTC, rosekc commented on docs/locales/zh_CN/LC_MESSAGES/appcontext.po
> +"Flask 在处理一个请求时候会自动 *推入* 一个应用上下文。视图函数，错误处理，还"
[#12](https://github.com/greyli/flask-docs-zh/discussions/12#discussioncomment-796182) 有讨论，待讨论结果落实到词汇表时统一修改

2021-06-15 12:47 UTC, rosekc commented on docs/locales/zh_CN/LC_MESSAGES/appcontext.po
> +"有其他在请求中运行的函数将会访问 :data:`current_app`。"
部分同意。这里没有`权限`的概念，因为本身上下文就不在了，所以不能访问，而不是上下文在，没有权利去访问。

2021-06-20 02:45 UTC, FesonX requested changes
基本没什么问题了 @rosekc 👍
@greyli 二审完成，请协助确定一下用不用翻译 `CLI`
CLI 是 Command Line Interface 的缩写，在 Flask 中可能还要加个 Clicks 的前缀，个人觉得保留缩写即可，没必要翻译

2021-06-20 02:45 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/appcontext.po
> +"Flask 在处理请求时候会自动 *推入* 一个应用上下文。视图函数，错误处理，还"
```suggestion
"Flask 在处理请求时候会自动 *推入* 一个应用上下文。视图函数、错误处理器、还"
```

2021-06-20 02:45 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/appcontext.po
> +"视图函数以及命令行命令下。"
@greyli

2022-01-23 08:22 UTC, FesonX approved these changes

2022-01-23 08:27 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/appcontext.po
> +"在视图函数与 :doc:`CLI commands </cli>` 中会用到。然而，在项目的模块里导入"
> 用不用翻译 CLI

我也认为不用翻译。不过这里的 commands 需要翻译，稍后我更新一下。

2022-01-23 08:33 UTC, greyli approved these changes

2022-01-23 08:33 UTC, merged