Translate docs/deploying/mod_wsgi @180909
flaskcwg/flask-docs-zh pull request #80
Opened 2021-06-13 13:04 UTC by 180909

- [x] 在 README.md 中勾选翻译的章节条目（把方括号里的空格替换为 `x`）.
- [x] 在本地生成文档并预览输出，处理所有错误和异常。
- [x] 运行 `pre-commit` 钩子，处理所有问题。
- [x] 更新 `.po` 文件顶部的 `Last-Translator` 字段。
- [x] 如果你是第一个翻译者，同时更新 `.po` 文件顶部的 `FIRST AUTHOR <EMAIL@ADDRESS>`，替换为你的名字和 Email 地址。

2021-08-28 02:48 UTC, FesonX requested changes
文章不长，但需要改动的地方不少。具体是**该省略的没省，需要翻译的没翻，表达还有待提高**。
请根据建议选择改动或者直接点按同意。

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"如果你使用的是 Ubuntu/Debian 系统，你可以使用如下的 apt-get 命令来安装："
```suggestion
"如果你使用的是 Ubuntu/Debian 系统，你可以使用如下的 apt-get 命令来安装并启用："
```
activate 不可省略

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"如果你使用的是基于 yum 的发行版（ Fedora, OpenSUSE 等等）的系统，你可以这样安装："
```suggestion
"如果你使用的是基于 yum 的发行版（Fedora, OpenSUSE 等等）的系统，你可以这样安装："
```
中文括号与单词之间不需要空格

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"在 FreeBSD 系统中，你可以通过编译 `www/mod_wsgi` 或是 pkg_add 来安装"
```suggestion
"在 FreeBSD 系统中，你可以通过编译 `www/mod_wsgi` 或是使用 pkg_add 来安装"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"文件中的 `application` 对象就是以后使用到的应用。"
```suggestion
"文件中的 `application` 对象就是之后使用到的应用。"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +msgstr "对大多数应用来说，文件中包含以下内容就足够了："
```suggestion
msgstr "对大多数应用来说，文件中包含以下内容就足够了::"
```
双冒号不译

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"如果你在 :file:`__init__.py` 文件中使用到了工厂函数，那么该函数应当被导入："
```suggestion
"如果你在 :file:`__init__.py` 文件中使用到了工厂函数，那么该函数应当被导入::"
```
同上

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"如果你的应用没有创建工厂函数，只是一个独立的实例，那么可以直接把实例导入为 "
```suggestion
"如果你没有一个用来创建应用的工厂函数，而是一个单例，那么可以直接把它导入为 "
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"把文件放在你能找得到的地方（比如： :file:`/var/www/yourapplication` ），并确保"
```suggestion
"把文件放在你能找得到的地方（比如：:file:`/var/www/yourapplication`），并确保"
```
同样不要在中文符号与英文间加空格

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +" `yourapplication` 和所有使用到的库都位于 pythonpath 中。如果你不想在系统环境中"
```suggestion
" `yourapplication` 和所有使用到的库都位于 python 加载路径中。如果你不想在系统环境中"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"下载库，你可以使用一个 `virtual python`_ 环境。请记住，最好将你的应用程序放入虚拟"
```suggestion
"安装，你可以考虑使用 `virtual python`_ 环境。请记住，最好将你的应用程序放入虚拟"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"环境中。有一个可选项是在 ``.wsgi`` 文件中，在导入前加入路径："
```suggestion
"环境中。有一个可选项是在导入前在 ``.wsgi`` 文件中加入路径::"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +msgstr "配置 Apache "
```suggestion
msgstr "配置 Apache"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"在一个不同的用户下执行应用程序，来展示它的安全性"
```suggestion
"我们让 `mod_wsgi` 在一个不同的用户下执行应用程序。"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"最后，你要为你的应用创建一个 Apache 配置文件。在下面的例子中，我们告诉 `mod_wsgi` "
```suggestion
"最后，你要为你的应用创建一个 Apache 配置文件。在下面的例子中，出于安全考虑，"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"注意： WSGIDaemonProcess 不能在 Windows 中实现，并且 Apache 将拒绝以上述配置"
```suggestion
"注意： WSGIDaemonProcess 未在 Windows 中实现，并且 Apache 将拒绝以上述配置"
```
isn't 不是 can't

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"最值得注意的是， httpd 2.2 的目录权限的语法"
```suggestion
"最值得注意的是， 目录权限的语法从 httpd 2.2 "
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +msgstr "改变为 httpd 2.4 的语法"
```suggestion
msgstr "变更为 httpd 2.4 的语法"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +msgstr "如果你的应用并没有启动，请按照以下指导排除故障："
```suggestion
msgstr "如果你的应用没有启动，请按照以下指导排除故障："
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +msgstr " **问题:** 应用无法启动，错误信息日志显示 SystemExit ignored "
```suggestion
msgstr " **问题:** 应用无法启动，错误信息显示 SystemExit ignored "
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"块中。要么把 :meth:`~flask.Flask.run` 函数放入一个单独的 :file:`run.py` 文件"
```suggestion
"要么把 :meth:`~flask.Flask.run` 的调用从文件移除，放入一个单独的 :file:`run.py` 文件"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"你的应用文件中有 ``app.run()`` 调用，但并未放入 ``if __name__ == '__main__':`` "
```suggestion
"你的应用文件中有 ``app.run()`` 调用，但并未放入 ``if __name__ == '__main__':``。"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"中，要么请将它让入 if 块中。"
```suggestion
"中，否则请将它让入 if 块中。"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +msgstr " **问题:** 权限问题"
```suggestion
msgstr " **问题:** 应用抛出权限错误"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +msgstr " **问题:** 打印时应用挂了"
```suggestion
msgstr " **问题:** 应用在打印时抛出错误终止"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +msgstr " **问题:** 打印时应用挂了"
太口语化

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"你可以把 `WSGIRestrictStdout` 设置为 ``off`` 以解决问题："
```suggestion
"你可以把 `WSGIRestrictStdout` 设置为 ``off`` 来关闭这个保护："
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"或者你也可以在 .wsgi 文件中设置使用不同的流替代标准流："
```suggestion
"或者你也可以在 .wsgi 文件中使用不同的流替代标准流："
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"你的应用可能是一个单独的 .py 文件，并且你把它符号连接到了 site-packages 文件夹中。"
```suggestion
"你的应用可能是一个单独的 .py 文件，并且你把它软连接到了 site-packages 文件夹中。"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"产生这种错误的原因是对于非安装包来说，模块的文件名用于定位资源，如果使用符号连接"
```suggestion
"产生这种错误的原因是对于非安装包来说，模块的文件名用于定位资源，如果使用软连接"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +" `mod_wsgi` 就会自动重新转入所有守护进程。"
```suggestion
"`mod_wsgi` 就会自动重新加载所有守护进程。"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"使用虚拟环境的优点是不必在系统中安装应用所需要的依赖，这样我们就可以更好地按照自己"
```suggestion
"使用虚拟环境的优点是不必在系统范围安装应用所需的依赖，这样就可以更好地控制"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"的需要进行控制。如果要在虚拟环境下使用 mod_wsgi ，那么我们要对 ``.wsgi`` 文件"
```suggestion
"哪里需要什么。如果要在虚拟环境下使用 mod_wsgi，那么我们要对 ``.wsgi`` 文件"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +msgstr "在你的 ``.wsgi`` 文件顶部加入下面这行："
```suggestion
msgstr "在你的 ``.wsgi`` 文件顶部加入下面这行::"
```

2021-08-28 02:48 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"这会根据虚拟环境的设置设置加载路径。请记住，路径必须是绝对的。"
```suggestion
"这会根据虚拟环境的设置设置加载路径。请记住，必须是绝对路径。"
```

2021-10-31 08:02 UTC, FesonX requested changes
后续此类错误较多，将打回由译者自行解决后再 Review
https://github.com/flaskcwg/flask-docs-zh/issues/11#issuecomment-943906242

2021-10-31 14:47 UTC, 180909 commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +msgstr " **问题：** 应用抛出权限错误"
**后面不加空格会导致Github Actions报错

2022-03-10 01:14 UTC, FesonX approved these changes

2022-03-10 01:14 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/deploying/mod_wsgi.po
> +"这会根据虚拟环境的设置设置加载路径。请记住，必须是绝对路径。"
```suggestion
"这样设置，就会根据虚拟环境的设置加载路径。请记住，必须是绝对路径。"
```

2022-05-08 08:48 UTC, merged