Translate docs/security
flaskcwg/flask-docs-zh pull request #82
Opened 2021-06-15 09:34 UTC by kylinbin

- [x ] 在 README.md 中勾选翻译的章节条目（把方括号里的空格替换为 `x`）.
- [x] 在本地生成文档并预览输出，处理所有错误和异常。
- [x] 运行 `pre-commit` 钩子，处理所有问题。
- [x] 更新 `.po` 文件顶部的 `Last-Translator` 字段。
- [x] 如果你是第一个翻译者，同时更新 `.po` 文件顶部的 `FIRST AUTHOR <EMAIL@ADDRESS>`，替换为你的名字和 Email 地址。

2021-06-15 11:27 UTC, greyli commented
> 不知道提交之后为什么显示英文原文的每句长度有变化，我是用 Poedit 来编辑的，并没有改动英文原文。

这是 Poedit 的问题（#36）。

2022-06-05 08:02 UTC, FesonX requested changes
翻译大体上没有什么问题，主要是中英文之间空格使用多余，或者括号未使用中文。
一些英文原文的长度变化问题，未做修正

2022-06-09 01:13 UTC, FesonX approved these changes

2022-06-09 01:14 UTC, FesonX commented
审核完毕 @greyli

2022-06-12 10:57 UTC, merged

2022-06-12 10:57 UTC, greyli commented
Merged, thanks!