Translate tutorial/docs
flaskcwg/flask-docs-zh pull request #83
Opened 2021-06-15 11:25 UTC by greyli

- [x] 在 README.md 中勾选翻译的章节条目（把方括号里的空格替换为 `x`）.
- [x] 在本地生成文档并预览输出，处理所有错误和异常。
- [x] 运行 `pre-commit` 钩子，处理所有问题。
- [x] 更新 `.po` 文件顶部的 `Last-Translator` 字段。
- [x] 如果你是第一个翻译者，同时更新 `.po` 文件顶部的 `FIRST AUTHOR <EMAIL@ADDRESS>`，替换为你的名字和 Email 地址。

2021-06-25 13:46 UTC, Sefank commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/static.po
> +"这个教程不会关注如何写 CSS，所以你可以直接复制下面的代码到 ``flaskr/static/style.css`` 文件："
这样翻译会不会好一点：
```suggestion
"在本教程中，你不需要关注如何编写 CSS 文件，因此你可以直接复制下面的代码到 ``flaskr/static/style.css`` 文件："
```

2021-06-25 13:49 UTC, Sefank commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/static.po
> +"认证视图和模板现在可以工作，但是看起来非常简陋。使用一些 `CSS`_ 可以给你编写的 "
“right now”修饰的是“they look very plain”这一句，我个人觉得应该改为：
```suggestion
"认证视图和模板能够正常使用，但是现在看起来还非常简陋。使用一些 `CSS`_ 可以给你编写的 "
```

2021-06-25 13:52 UTC, Sefank commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/static.po
> +"你可以在 `Mozilla 文档 <CSS_>`_ 阅读更多关于 CSS 的内容。如果静态文件产生了变化"
```suggestion
"你可以在 `Mozilla 文档 <CSS_>`_ 阅读更多关于 CSS 的内容。如果修改了某一静态文件"
```

2021-06-25 13:53 UTC, Sefank requested changes
有一点点翻译的建议，仅供参考

2021-06-25 14:33 UTC, greyli commented
@Sefank 谢谢~

2022-01-28 10:11 UTC, FesonX requested changes

2022-01-28 10:11 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/static.po
> +"除了 CSS，还有其他类型的静态文件比如 JavaScript 或是 logo 图片。它们都需要放在 "
```suggestion
"除了 CSS，还有其他类型的静态文件比如 JavaScript 函数或是 logo 图片。它们都需要放在 "
```

2022-01-28 10:11 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/static.po
> +msgstr "登陆页面截图"
```suggestion
msgstr "登录页面截图"
```

2022-02-08 16:23 UTC, merged