Translate patterns/sqlalchemy
flaskcwg/flask-docs-zh pull request #87
Opened 2021-06-17 23:28 UTC by wnykuang

1. Engine 在这里应该指的只是那个变量的名字，翻译成引擎相当于徒增术语，没什么好翻的。
2. 我不知道注释要不要翻，如果需要翻就跟我说一下就行。

- [x] 在 README.md 中勾选翻译的章节条目（把方括号里的空格替换为 `x`）.
- [x] 在本地生成文档并预览输出，处理所有错误和异常。
- [x] 运行 `pre-commit` 钩子，处理所有问题。
- [x] 更新 `.po` 文件顶部的 `Last-Translator` 字段。
- [x] 如果你是第一个翻译者，同时更新 `.po` 文件顶部的 `FIRST AUTHOR <EMAIL@ADDRESS>`，替换为你的名字和 Email 地址。

2021-06-18 07:33 UTC, wnykuang commented on docs/locales/zh_CN/LC_MESSAGES/patterns/sqlalchemy.po
> +"使用包（ package ）而不是使用单独使用一整个模块（module）。 "
nit: 后面的括号

2021-06-18 07:44 UTC, wnykuang commented on docs/locales/zh_CN/LC_MESSAGES/patterns/sqlalchemy.po
> +msgstr "声明"
Declarative 应该是声明式，声明式定义数据模型

2021-06-25 15:27 UTC, frostming requested changes
review了部分，存在较大问题，建议参考回复重新斟酌语句，谢谢

2021-06-25 15:27 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/patterns/sqlalchemy.po
> +"很多人通过 `SQLAlchemy`_ 来进行数据库的访问。在这种情况下，我们推荐在你的 flask 应用中"
```suggestion
"很多人通过 `SQLAlchemy`_ 来访问数据库。在这种情况下，我们推荐在你的 flask 应用中"
```
小小的西式中文的改正

2021-06-25 15:27 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/patterns/sqlalchemy.po
> +"使用包（ package ）而不是使用单独使用一整个模块（module）。 "
```suggestion
"使用包（package）而不是使用单独使用一整个模块（module）。"
```
中文标点与英文之间不用空格，下同。注意多余的空格。

2021-06-25 15:27 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/patterns/sqlalchemy.po
> +"接下来将会介绍四种常用的 SQLAlchemy 使用方式: "
```suggestion
"接下来将会介绍四种常用的 SQLAlchemy 使用方式："
```
请在（不影响restructuredtext语法的情况下）换用中文标点。

2021-06-25 15:27 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/patterns/sqlalchemy.po
> +"Flask-SQLAlchemy 插件"
```suggestion
"Flask-SQLAlchemy 扩展"
```
plugin -> 插件

2021-06-25 15:27 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/patterns/sqlalchemy.po
> +"作为一种数据库抽象层和对象关系映射器， SQLAlchemy 十分流行且易用。早已有人实现了对应的Flask 插件。"
遗漏原句的语意，请重翻这段，并且不要留下多余的空格（中文标点与英文之间无需空格）

2021-06-25 15:27 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/patterns/sqlalchemy.po
> +"/Flask-SQLAlchemy/>`_."
可以直译的没必要意译

2021-06-25 15:27 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/patterns/sqlalchemy.po
> +"我推荐各位查看一下 `声明`_ 的官方文档作为对本文档的补充。"
缺失严重，请重翻这段

2021-06-25 15:27 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/patterns/sqlalchemy.po
> +msgstr "示例: :file:`database.py`"
可以直译的没必要意译

2023-03-22 23:14 UTC, closed without merging